[DEFAULT]
host = localhost
port = 9002
is_secure = False
ssl_verify = False

[fixtures]
bucket prefix = powerfs-{random}-

[s3 main]
display_name = PowerFS Tester
user_id = testid
email = tester@ceph.com
api_name = default
access_key = powerfs
secret_key = powerfs123

[s3 alt]
display_name = john.doe
email = john.doe@example.com
user_id = 56789abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234
access_key = powerfsalt
secret_key = powerfsalt123

[s3 tenant]
display_name = testx$tenanteduser
user_id = 9876543210abcdef0123456789abcdef0123456789abcdef0123456789abcdef
access_key = powerfs
secret_key = powerfs123
email = tenanteduser@example.com
tenant =

[iam]
email = s3@example.com
user_id = 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
access_key = powerfs
secret_key = powerfs123
display_name = powerfsuser

[iam root]
access_key = powerfs
secret_key = powerfs123
user_id = RGW11111111111111111
email = account1@powerfs.local

[iam alt root]
access_key = powerfsalt
secret_key = powerfsalt123
user_id = RGW22222222222222222
email = account2@powerfs.local